### ISSUE TITLE
No module named 'cluster'

### ISSUE THREAD

**Issue by shlokk** [xu-ji/IIC#1]
Hi, I'm getting import issues. Also, I have changed code to code1 as it was causing some dependency issues.
CUDA_VISIBLE_DEVICES=0,1,2,3 python -m code1.scripts.segmentation.segmentation_twohead --mode IID --dataset Coco164kCuratedFew --dataset_root /scratch/local/ssd/xuji/COCO/CocoStuff164k --model_ind 714 --arch SegmentationNet10aTwoHead --num_epochs 4800 --lr 0.0001 --lamb_A 1.0 --lamb_B 1.0 --num_sub_heads 1 --batch_sz 120 --num_dataloaders 1 --use_coarse_labels --output_k_A 15 --output_k_B 3 --gt_k 3 --pre_scale_all --pre_scale_factor 0.33 --input_sz 128 --half_T_side_sparse_min 0 --half_T_side_sparse_max 0 --half_T_side_dense 10 --include_rgb  --coco_164k_curated_version 6 --use_uncollapsed_loss --batchnorm_track > gnoded2_gpu0123_m714.out
Traceback (most recent call last):
  File "/vulcan/scratch/shlok/Ana/envs/pytorch/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/vulcan/scratch/shlok/Ana/envs/pytorch/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/vulcan/scratch/shlok/IIC/code1/scripts/segmentation/segmentation_twohead.py", line 18, in <module>
    import code1.archs as archs
  File "/vulcan/scratch/shlok/IIC/code1/archs/__init__.py", line 1, in <module>
    from cluster import *
ImportError: No module named 'cluster'

**Comment by xu-ji** [comment]
That is strange, I just ran the code. There should not be any dependency issues with code -> code1 as there is nothing else called code.

It sounds like it could be a current working directory issue. Try avoiding runpy.py. Go inside the top level IIC repository and run the command manually on the command line from there. Consider git reset to undo your changes first.

**Comment by shlokk** [comment]
Hi It was python issue, I was running it on python3, while it should be run on python2.

**Comment by zjgt** [comment]
I had the same problem, and solved it by adding "." in front of the name to indicate current directory.
