### ISSUE TITLE
Computing IID_loss and get a negative result.

### ISSUE THREAD

**Issue by hhc1997** [xu-ji/IIC#114]
Hello, I computed IID_loss, but the result is negative （approximate to zero). Is it right?

**Comment by WeiWenQiang123456** [comment]
I got same result.This question puzzled me for a long time, if you know what the reason, please tell me

**Comment by aurban0** [comment]
@WeiWenQiang123456 @hhc1997 We want to maximise IID loss. What we are actually doing is to minimize the negative IID loss. Because IID is always non-zero, maximising negative IID will always show negative values
