### ISSUE TITLE
How to visualize segmentation results?

### ISSUE THREAD

**Issue by hriaz17** [xu-ji/IIC#15]
Using the pre-trained model 544, I want to visualize the results of the image segmentation on Potsdam-3 as given in Figure 7 of the IIC research paper. However, downloading the models from the link given in README.MD only gives me the config files for the training. How do I execute the models to see the unsupervised segmentation in action?

**Comment by xu-ji** [comment]
Hi, 
The model used in figure 7 is 545, Potsdam-3. I uploaded the rendering script [here](https://github.com/xu-ji/IIC/blob/master/code/scripts/segmentation/analysis/render_potsdam.py).
