### ISSUE TITLE
lamb parameter

### ISSUE THREAD

**Issue by hoangdzung** [xu-ji/IIC#16]
Have you investigated how the lamb affects the performance of model? Tuning it helps me getting a better result, but I don't see anything about it on the paper?

**Comment by xu-ji** [comment]
The lambda parameter is not used (i.e. set to 1) for most experiments, including all clustering experiments. For segmentation we play around with it and found some minor improvements. 

It is discussed in 2 places, in the paper in section 4.2 "training", and in supplementary materials section 5. If you look in commands.txt you can see models 555 and 545 use lambda=1.5, and 714 and 711 are the same experiments except with lambda=1.

**Comment by hoangdzung** [comment]
Thank you, @xu-ji 
How can I get the supplementary material?

**Comment by hoangdzung** [comment]
Thank you, @xu-ji

**Comment by vivektreddy** [comment]
Thank you.  So is the additional lambda term like regularization.  I(z|z') + (lambda-1)( H(z) + H(z')).  Does this lambda act like a penalty term that forces H(z) and H(z') values to be higher and H(z|z') not to be focused on?  What does this mean theoretically?  How would it change the cluster space?  Thank you.
