### ISSUE TITLE
Do not work on new Dataset

### ISSUE THREAD

**Issue by MrAcademic** [xu-ji/IIC#23]
Do you think for this dataset
https://github.com/Kai-Xuan/ETH-80
Does 18% acc for unsupervised make sense?

Do you have any idea for setting parameter?

**Comment by xu-ji** [comment]
Hi, if it's 8 classes, random performance is 12.5%. So 18% is not great. 

It is up to you to experiment with hyper parameters, following general common sense for training networks.
