### ISSUE TITLE
Supplementary Material

### ISSUE THREAD

**Issue by yassouali** [xu-ji/IIC#24]
Hi, first of all, thanks for the amazing work,

Sorry if this is not the place to ask this type of question, feel free to close the issue; Since you've mentioned the sum. mat in the paper quite a few time, I was wandering where can I find the supplementary material of your paper. 

Thanks.

**Comment by yassouali** [comment]
My bad, just found it, sorry :) !

**Comment by msalvaris** [comment]
In case anyone else comes looking it is here https://github.com/xu-ji/IIC/blob/master/paper/suppmat_camera_ready.pdf
