### ISSUE TITLE
Some questions about training time

### ISSUE THREAD

**Issue by yassouali** [xu-ji/IIC#25]
Hi, first thanks for the amazing work and providing the code.

I am testing my model on potsdam-3 for unsupervised segmentation, with only two P100 (so 24 GB), the batch size if quite small, and in your example command you have 4800 epochs, which is a lot (that might take me like more than a month to complete), I was wandering if I am doing something wrong or is the training time is indeed this long? and can you please provide just some metrics, like the number of epochs needed for good performance in your experiments and the minimal loss values we can expect?

 Thanks again for this work.

**Comment by xu-ji** [comment]
Hi, the 4800 epochs is just some upper bound which is never fully utilised. If you [download the saved models and files](https://github.com/xu-ji/IIC/blob/master/examples/trained_models.txt), you can see the graphs for accuracy per epoch for each model. 

For Potsdam-3, model 545, you can see that best accuracy was reached in 5 epochs, and stays there (approx) after that. I looked at my printing logs and saw each epoch took about 13 minutes, including about 1 minute for evaluation.

**Comment by yassouali** [comment]
Thank you, I thought I've seen the graphs in an earlier version but couldn't find them :)!

**Comment by DonkeyShot21** [comment]
Hi, sorry for reopening this. I am trying to reproduce your results using your code. In particular, I want to train model 640 (CIFAR 10, sobel, two heads) using a Tesla K40. It takes approx 1h20min for each epoch which is a lot. I tried using multiple GPUs (K40) but it didn't help, it looked even slower. Also, I downloaded your trained models and I saw you need more or less 1k epochs in order for the model to properly converge. Doing the maths it looks like it will be done in some months. What hardware did you use? Did you train on multiple GPUs?
