### ISSUE TITLE
How to install javapackages==1.0.0?

### ISSUE THREAD

**Issue by Jian-danai** [xu-ji/IIC#26]
I cannot pip install javapackages==1.0.0?
_ERROR: Could not find a version that satisfies the requirement javapackages==1.0.0 (from versions: none)
ERROR: No matching distribution found for javapackages==1.0.0_

**Comment by xu-ji** [comment]
I think this package is not important. The code doesn't use java. You can probably just skip installing it.

**Comment by Jian-danai** [comment]
meld==3.16.4 cannot be installed either.
(Sorry for the bothering, just installed...)

**Comment by ZJUJeffLai** [comment]
meld==3.16.4 cannot be installed either.....I still cannot install it.

**Comment by xu-ji** [comment]
@ZJUJeffLai I don't think this is used in the code, you can probably skip it.
