### ISSUE TITLE
Error when training model: "Unsupported operation"

### ISSUE THREAD

**Issue by nickpezzotti1** [xu-ji/IIC#27]
Running this command on a gpu colab notebook:
`export CUDA_VISIBLE_DEVICES=0 && python -m code.scripts.cluster.cluster_greyscale_twohead --model_ind 0 --arch ClusterNet6cTwoHead --mode IID --dataset_root /code/utils/cluster/MNIST.py --gt_k 10 --output_k_A 10 --output_k_B 10 --lamb_A 1.0 --lamb_B 1.0 --lr 0.0001 --num_epochs 3200 --batch_sz 10 --num_dataloaders 1 --num_sub_heads 1 --crop_orig --crop_other --tf1_crop centre_half --tf2_crop random --tf1_crop_sz 20 --tf2_crop_szs 16 20 24 --input_sz 24 --rot_val 25 --no_flip --head_B_epochs 2 `

Gets this error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/content/code/code/scripts/cluster/cluster_greyscale_twohead.py", line 495, in <module>
    train()
  File "/content/code/code/scripts/cluster/cluster_greyscale_twohead.py", line 378, in train
    avg_loss_batch.backward()
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python2.7/dist-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before performing the operation.

**Comment by xu-ji** [comment]
What is your pytorch version?

**Comment by nickpezzotti1** [comment]
1.3.0+cu100

**Comment by xu-ji** [comment]
The code was written for an earlier version of pytorch: https://github.com/xu-ji/IIC/blob/master/package_versions.txt#L114

**Comment by mitmul** [comment]
@nickpezzotti1 I think fixing the below three lines will resolve this issue.

In `code/utils/cluster/IID_losses.py`:
```diff
-  p_i_j[(p_i_j < EPS).data] = EPS
-  p_j[(p_j < EPS).data] = EPS
-  p_i[(p_i < EPS).data] = EPS
+  p_i_j = torch.where(p_i_j < EPS, torch.ones_like(p_i_j) * EPS, p_i_j)
+  p_j = torch.where(p_j < EPS, torch.ones_like(p_j) * EPS, p_j)
+  p_i = torch.where(p_i < EPS, torch.ones_like(p_i) * EPS, p_i)
```

**Comment by xu-ji** [comment]
You can use `.detach()` in place of `.data` in those lines.
