### ISSUE TITLE
About the scope of the IID_loss

### ISSUE THREAD

**Issue by Orlando17** [xu-ji/IIC#29]
Hi! I apply the function of  IID_loss in the object classification and the loss is negative.  And the accuracy decrease in the training process. Is there something wrong? Thank you for answering!

**Comment by xu-ji** [comment]
Loss is supposed to be negative because mutual information is nonnegative. What data is it? Can you share your loss and accuracy graphs please?

**Comment by Orlando17** [comment]
The dataset is MS COCO and I used IID_loss for box classification in the detection framework. 
![image](https://user-images.githubusercontent.com/22490365/67821717-ea39ca00-faf8-11e9-9697-097b49017d27.png)
![image](https://user-images.githubusercontent.com/22490365/67821740-02a9e480-faf9-11e9-9748-aa5a0ffe0ceb.png)

**Comment by xu-ji** [comment]
The loss becomes more negative which suggests the IIC objective is being correctly optimised.

You seem to be using several other losses; mse loss, p loss etc. These will also be influencing accuracy. Could they be removed? In our experiments we only use the IIC loss.

Can you describe the task and model in more detail; you are doing image classification on predefined box crops of COCO images? How many clusters are you using? Are you using auxiliary overclustering? How many ground truth classes are there?
