### ISSUE TITLE
Estimation of the joint distribution

### ISSUE THREAD

**Issue by jizongFox** [xu-ji/IIC#31]
Hello @xu-ji ,

May I ask you why estimating the joint `P(X,Y) =P(X)×P(Y)` holds in your equation? 
It holds when `X` and `Y` are independent, It is obvious that `P(X)` and `P(T(X))` are dependent. I may regard it as `biased`.
You maximize the MI based on the average on `z` of `P(X|Z)×P(Y|Z)`, where `z` is an image, does the average of the product helps to reduce this `bias`?

**Comment by xu-ji** [comment]
Thanks for the question. We use `z` to denote class and `x` to denote image in the paper, so I'll continue with that here. 

Given images `x` and `x' = g(x)`, class variables `z|x` and `z’|x’` are independent but `z` and `z’` are not. And we want to model information between `z` and `z’`.

So `p(z, z') != p(z)p(z')`, you are right about this.

But `p(z, z'| x, x') = p(z | x, x') * p(z' | x, x') =  p(z | x) * p(z' | x')`, as the latter are independent (i.e. note the conditioning on the image already being given).

So then `p(z, z') = sum_{x, x'} p(z, z', x, x') = sum_{x, x'} p(z, z'| x, x') p(x, x')` where `p(x, x')` is a constant `1/N`, `N` is the size of the data. Which is what we do.

**Comment by jizongFox** [comment]
I am not sure to understand why this holds:
`p(z, z'| x, x') = p(z | x, x') * p(z' | x, x')`, could you please give more details?

**Comment by xu-ji** [comment]
I think it's conditional independence. Given you already know `x, x'`, knowledge of what `z` occurs gives no *additional* information about what `z'` occurs.

**Comment by jizongFox** [comment]
Here `x` and `x'` is the same image after getting basic and advanced transformation. Saying that `z` has two classes, `cat` and `dog`, when `z` is close to `dog`, `z'` seems to be a `dog` as well. Therefore, do `z` and `z'` be conditionally independent given `x` and `x'`?
I don't know if this kind of comparison works in the setting.

**Comment by xu-ji** [comment]
`z | x, x' `and `z' | x, x'` are not the same variables as `z` and `z'`.

As you say, when `z` is close to dog, `z'` is probably a dog too. But that information is already fully given by `x'`, which is an image of a dog. Knowing `z` helps when you don't know `x'`, but doesn't if you do know `x'`. Just from `x'` it should already be known that the class is dog.

**Comment by jizongFox** [comment]
Thanks for the explanation!
