### ISSUE TITLE
what's the explanation of datasets code

### ISSUE THREAD

**Issue by yaochx** [xu-ji/IIC#38]
in the file (code/datasets/segmentation/cocostuff.py), what operations is done with datsets.

between the following datasets, what's the difference? or where should i refer to 
Coco10kFull
Coco10kFew
Coco164kFull
Coco164kFew
Coco164kCuratedFew
Coco164kCuratedFull

**Comment by yaochx** [comment]
from example/commands.txt, you've given the scripts to train, so only the latter curated datasets are used or implemented. in §4.2 segmentation DATASETS, you have explained the difference within datasets COCO-Stuff-3 and COCO-Stuff. 

COCO-Stuff-3 (555)
--dataset Coco164kCuratedFew --dataset_root /data/cocostuff164k/

COCO-Stuff-3 no lambda coefficient (714)
--dataset Coco164kCuratedFew --dataset_root /scratch/local/ssd/xuji/COCO/CocoStuff164k

COCO-Stuff (512)
--dataset Coco164kCuratedFull --dataset_root /scratch/local/ssd/xuji/COCO/CocoStuff164k

Now I'm trying to understand the cocostuff dataset preparation.

**Comment by xu-ji** [comment]
"Few" means 3 classes, these are 3 supersets of the COCO stuff classes, hence COCO-Stuff-3. "Full" means all the classes.

Curated means cleaned. It's the images in the dataset where at least 75% of pixels are COCO stuff classes (as opposed to COCO things). The [script](https://github.com/xu-ji/IIC/blob/master/code/datasets/segmentation/util/coco164k_prepare.py)
