### ISSUE TITLE
Training time for CIFAR10

### ISSUE THREAD

**Issue by xuw080** [xu-ji/IIC#40]
Thank you for releasing your codes! I tried to run your codes on CIFAR10 recently. According to the provided command, the totally epochs you set is 2000. I am using 4 RTX 2080ti GPUs to run your codes. It need to take about 10 minutes for each epoch. Therefore, the totally time cost for training CIFAR10 with 4 GPUs will be about 14 days, which is too long. I am not whether I did something wrong, or it indeed need 14 days? Thank you!

**Comment by jizongFox** [comment]
It takes very longtime

**Comment by xu-ji** [comment]
Hi, for us best performance was achieved in ~12 days, 60% acc in ~4 days. See [this post](https://github.com/xu-ji/IIC/issues/4#issuecomment-565511225)
