### ISSUE TITLE
Training with Potsdam dataset cuda out of memory

### ISSUE THREAD

**Issue by lilyylil** [xu-ji/IIC#41]
hi~
I am training the segmentation code with Potsdam dataset. When the model starts to iterate the GPU memory increasing rapidly and will always out of memory,
![outof](https://user-images.githubusercontent.com/37561837/71777799-2cdbbf00-2fe0-11ea-83c9-16b5915206f9.png)
I'm using 8 1080TI and my bach size is 2.
My training scrip is 
python -u -m code.scripts.segmentation.segmentation_twohead --mode IID --dataset Potsdam --dataset_root /mnt/lustre/lichuchen/lily/unsupervise/dataset/POTSDAM --model_ind 544 --arch SegmentationNet10aTwoHead --num_epochs 4800 --lr 0.000001 --lamb_A 1.0 --lamb_B 1.0 --num_sub_heads 1 --batch_sz 2 --num_dataloaders 1 --output_k_A 36 --output_k_B 6 --gt_k 6 --input_sz 200 --half_T_side_sparse_min 0 --half_T_side_sparse_max 0 --half_T_side_dense 5  --include_rgb --no_sobel --jitter_brightness 0.1 \
 --jitter_contrast 0.1 --jitter_saturation 0.1 --jitter_hue 0.1 --use_uncollapsed_loss --batchnorm_track

Could you tell me the memory usage of your segmentation code?
Thanks~

**Comment by xu-ji** [comment]
I ran the original command for 544 (Potsdam) on 4x Tesla P40 (24GB each). I ran the simpler 3 classes version 545 (Potsdam-3) on 2x Tesla P40 (24GB each).

**Comment by lilyylil** [comment]
Thanks for your time~and can you tell me the training time for Postdam and coco-stuff164k?

**Comment by xu-ji** [comment]
I uploaded some more [logs](https://github.com/xu-ji/IIC/blob/master/examples/logs_segmentation.tar.gz) where you can see timestamps. If you download the trained models and plots you can see when best performance was reached. Time till best performance:
- 555, COCO-stuff-3. 27 epochs (one per head): ~14 hrs. 
- 512, COCO-stuff. 7 epochs (one per head): ~23 hrs.
- 545, Potsdam-3. 5 epochs (one per head): ~1.5 hrs.
- 544, Potsdam. 4 epochs (one per head): ~2 hrs.

**Comment by lilyylil** [comment]
Thank you very much!

**Comment by lilyylil** [comment]
Sorry to bother you again, but when I check your training log for cocostuff(two heads B,A, number of clusters are15 and 45, respectively), it seems that you will train your model with the order of heads [A,B]. 
But in your released code and training commends, the model will start with head B first, can you tell me why the order is different?
And also it seems that in your log, an epoch will only contain one head, but the released code shows that one epoch will contain two heads, will this affect the training results?
Correct me if I'm wrong.
Thank you for your time~

**Comment by xu-ji** [comment]
I think you may have an older version of the code; a while back I changed the script back to default to [head A first](https://github.com/xu-ji/IIC/blob/master/code/scripts/segmentation/segmentation_twohead.py#L180) by default, so the commands provided do start training head A first.

Training both heads in one "epoch" was a change I made later, you are right. I think I did this to make the segmentation script consistent with the clustering script. But this is not a material change, just that the nominal number of epochs needed to train will be half. I.e. this should not materially affect the training results.
