### ISSUE TITLE
IID_segmentation_loss_uncollapsed ?

### ISSUE THREAD

**Issue by jizongFox** [xu-ji/IIC#45]
Hi, 
Could you please tell me what is the different between `IID_segmentation_loss` and `IID_segmentation_loss_uncollapsed`?
I saw the difference as the normalization towards `padding`.

**Comment by xu-ji** [comment]
Yep, the difference is the normalisation. We use `IID_segmentation_loss_uncollapsed` for our results, but an alternative is `IID_segmentation_loss`. This is discussed in section 6 of the supplementary material.
