### ISSUE TITLE
How to load pre-trained model

### ISSUE THREAD

**Issue by nickpezzotti1** [xu-ji/IIC#47]
How do you recommend loading a pre-trained model? In particular, I am working with model-ind 685 (MNIST - unsupervised).

**Comment by keliive** [comment]
Similar question for model-ind 544 using Potsdam dataset for fully unsupervised segmentation. The config.pickle file seems to not work.

**Comment by keliive** [comment]
@nickpezzotti1 how did you solve it?

**Comment by nickpezzotti1** [comment]
```
import pickle
import torch
import code.archs as archs

config_in = open("/content/code/config.pickle", "rb")
config = pickle.load(config_in)
net = archs.__dict__[config.arch](config)
net.load_state_dict(torch.load("/content/code/best_net.pytorch"))
```

**Comment by maaira** [comment]
@nickpezzotti1 I'm trying to load model 714 using your code but i'm getting this error:
`from code.archs import archs`
`ImportError: No module named archs`

**Comment by nickpezzotti1** [comment]
check you are in the correct directory. 

Also check you are using python 2.

**Comment by jizongFox** [comment]
Try to not use Pycharm

**Comment by maaira** [comment]
Thank you, the problem as the python version in the conda env

**Comment by Limzui** [comment]
Hi, may I know if anyone here knows how to run inference only on a dataset after loading a pre-trained network? 

For example after loading ind 685, how do I only run inference on MNIST test set?

The commands given in commands.txt seem to be for training from scratch

**Comment by ramprs** [comment]
Hi @Limzui, I have the same question. If you have figured this out, could you tell me how I can just run inference on the test set to create segmentation maps? Thanks in advance

**Comment by OmarHedeya95** [comment]
Hey, did anyone figure out how to just run the pre-trained model for infrence?

**Comment by OmarHedeya95** [comment]
@ramprs did you figure it out?
