### ISSUE TITLE
pretrained model and inference code

### ISSUE THREAD

**Issue by betterze** [xu-ji/IIC#48]
Dear IIC group,

Thank you for sharing with us this wonderful project. Just have a simple question. 

The model in this link 'https://www.robots.ox.ac.uk/~xuji/models/models.tar.gz' is for mnist or STL dataset? I want to try it on STL dataset. And do you have a example code for inference?

Thank you very much for your help.

Best Wishes,

Alex

**Comment by xu-ji** [comment]
That zip file contains files for many models. Unzip it and you can determine which subdirectory you need using the [commands](https://github.com/xu-ji/IIC/blob/master/examples/commands.txt). The command will direct you to the right script, which performs training and evaluation, that you can modify to do whatever you want. E.g. for STL10 this is model 569 and the `code.scripts.cluster.cluster_sobel_twohead` script.

**Comment by betterze** [comment]
Thx, I thought the number in each folder was epoch number. Now I understand it.
