### ISSUE TITLE
How to understand "auxiliary overclustering" ?

### ISSUE THREAD

**Issue by HellFireC02** [xu-ji/IIC#51]
As you show the fig.2 in your paper, auxiliary overclustering can used to improve cluster quality.
I read your code, and i notice that you produce 2 datasets called **"dataloaders_head_A"** and **"dataloaders_head_B"**. 
I think you alternately use these two datasets for model training and share parameters among them.
But the model need have a fixed "num_classes", which means parameters of the last few layers of the model cannot be shared. 
Specifically, I want to use the "auxiliary overclustering" to my image clustering for a specific task. 
But i think just creating a dataloader will be ok.  If I just modify the num_classes of the model alternately during training on the same dataloader, can I achieve this "auxiliary overclustering"?

Namely, can you explain brief steps of the "auxiliary overclustering" ?

**Comment by xu-ji** [comment]
> If I just modify the num_classes of the model alternately during training on the same dataloader, can I achieve this "auxiliary overclustering"

I don't think you should modify num_classes. You probably can use the same dataloaders for both heads. I made them separate, because for STL10 we wanted to have one head trained on the main 5k images and the other head trained on the main 5k + 100k auxiliary images. For the other datasets, the data and therefore the dataloaders for the two heads are identical copies.

**Comment by HellFireC02** [comment]
Sorry, I still don't quite understand what you mean.
You think i shouldn't modify the "num_classes" of the model. But you know a certain model must have a fixed  "num_classes". And "auxiliary overclustering" need another "num_classes" called "output_k_A" in your code.
I read your code in code/archs/cluster/net5g_two_head.py . I notice that:
**def forward(self, x, head="B", kmeans_use_features=False,
              trunk_features=False,
              penultimate_features=False):
    # default is "B" for use by eval code
    # training script switches between A and B
    x = self.trunk(x, penultimate_features=penultimate_features)
    if trunk_features:  # for semisup
      return x
    # returns list or single
    if head == "A":
      _x = self.head_A(x, kmeans_use_features=kmeans_use_features)_
    elif head == "B":
      _x = self.head_B(x, kmeans_use_features=kmeans_use_features)_
    else:
      assert (False)**
It seems you create two models and set different "num_classes" to them.
(the 2 models called head_A and head_B)
If what i think is right, i can understand your words(i shouldn't modify num_classes).
However, since the **two models** are trained alternately, how do they share parameters?

**Comment by xu-ji** [comment]
head_A and head_B are just linear layers. They are different but they share the CNN that goes before them. As in figure 2 in the paper.

**Comment by HellFireC02** [comment]
I understand, head_A and head_B are all linear layers. But they have different "num_classes" called output_k_A(overcluster) and output_k_B. They share a common CNN and all of them form **one** complete model. But the last linear layer of this model has two different types(overcluster and normal).
The model is trained with these two linear layers alternately.
So you think i shouldn't modify "num_classes", but i can create two different linear layers(with two different "num_classes") and connect them to a common CNN. (like what you do)
Can I understand your words correctly?

**Comment by xu-ji** [comment]
I think I do not actually use any variable `num_classes`.

> can create two different linear layers(with two different "num_classes") and connect them to a common CNN. (like what you do)

Yes.

**Comment by HellFireC02** [comment]
'num_classes' just represents variable like 'output_k_A' and 'output_k_B'  etc. 
now I understand completely. 
thanks for your kindly help!
