### ISSUE TITLE
Pretrained models for Doersch and Isola baselines

### ISSUE THREAD

**Issue by SDNAFIO** [xu-ji/IIC#52]
Are there any pretrained models for the baselines available?
Respectively can you provide the exact settings that were used to reproduce the results presented in the paper?

**Comment by xu-ji** [comment]
Download:
`wget https://www.robots.ox.ac.uk/~xuji/models/doersch_isola_models.tar.gz`

Commands:

Doersch:
550 COCO-Stuff-3
`export CUDA_VISIBLE_DEVICES=0,1 && nohup python -m code.scripts.segmentation.baselines.doersch --model_ind 550 --arch SegmentationNet10aDoersch  --dataset Coco164kCuratedFew --dataset_root /scratch/local/ssd/xuji/COCO/CocoStuff164k --coco_164k_curated_version 6 --use_coarse_labels --gt_k 3 --lr 0.00001 --batch_sz 140 --max_num_kmeans_samples 50000000 --include_rgb --pre_scale_all --pre_scale_factor 0.33 --input_sz 128 --doersch_patch_side 11 > gnoded2_gpu01_m550.out &`

551 COCO-Stuff
`export CUDA_VISIBLE_DEVICES=2,3 && nohup python -m code.scripts.segmentation.baselines.doersch --model_ind 551 --arch SegmentationNet10aDoersch  --dataset Coco164kCuratedFull --dataset_root /scratch/local/ssd/xuji/COCO/CocoStuff164k --coco_164k_curated_version 7 --use_coarse_labels --gt_k 15 --lr 0.00001 --batch_sz 140 --max_num_kmeans_samples 50000000 --include_rgb --pre_scale_all --pre_scale_factor 0.33 --input_sz 128 --doersch_patch_side 11  >  sh13_gpu23_m551.out &`

542 Potsdam-3
`export CUDA_VISIBLE_DEVICES=2,3 && nohup python -m code.scripts.segmentation.baselines.doersch --model_ind 542 --arch SegmentationNet10aDoersch  --dataset Potsdam --dataset_root /scratch/local/ssd/xuji/POTSDAM --use_coarse_labels --gt_k 3 --lr 0.0001 --batch_sz 60 --jitter_brightness 0.1 --jitter_contrast 0.1 --jitter_saturation 0.1 --jitter_hue 0.1 --max_num_kmeans_samples 10000000 --no_sobel --include_rgb --input_sz 200 --doersch_patch_side 11 > sh13_gpu23_m542.out &`

546 Potsdam
`export CUDA_VISIBLE_DEVICES=3,2 && nohup python -m code.scripts.segmentation.baselines.doersch --model_ind 546 --arch SegmentationNet10aDoersch  --dataset Potsdam --dataset_root /scratch/local/ssd/xuji/POTSDAM --gt_k 6 --lr 0.00001 --batch_sz 60 --jitter_brightness 0.1 --jitter_contrast 0.1 --jitter_saturation 0.1 --jitter_hue 0.1 --max_num_kmeans_samples 10000000 --no_sobel --include_rgb --input_sz 200 --doersch_patch_side 11 > gnodee3_gpu32_m546.out &`

Isola:

534 COCO-Stuff-3
`export CUDA_VISIBLE_DEVICES=0,1 && nohup python -m code.scripts.segmentation.baselines.isola --model_ind 534 --arch SegmentationNet10aIsola  --dataset Coco164kCuratedFew --dataset_root /scratch/local/ssd/xuji/COCO/CocoStuff164k --coco_164k_curated_version 6 --use_coarse_labels --gt_k 3 --lr 0.00001 --batch_sz 140 --max_num_kmeans_samples 50000000 --include_rgb --pre_scale_all --pre_scale_factor 0.33 --input_sz 128 --isola_patch_side 11  > gnodec4_gpu01_m534.out &`

535 COCO-Stuff
`export CUDA_VISIBLE_DEVICES=2,3 && nohup python -m code.scripts.segmentation.baselines.isola --model_ind 535 --arch SegmentationNet10aIsola  --dataset Coco164kCuratedFull --dataset_root /scratch/local/ssd/xuji/COCO/CocoStuff164k --coco_164k_curated_version 7 --use_coarse_labels --gt_k 15 --lr 0.00001 --batch_sz 140 --max_num_kmeans_samples 50000000 --include_rgb --pre_scale_all --pre_scale_factor 0.33 --input_sz 128 --isola_patch_side 11 > gnodec4_gpu23_m535.out &`

532 Potsdam-3
`export CUDA_VISIBLE_DEVICES=3,2 && nohup python -m code.scripts.segmentation.baselines.isola --model_ind 532 --arch SegmentationNet10aIsola  --dataset Potsdam --dataset_root /scratch/local/ssd/xuji/POTSDAM --use_coarse_labels --gt_k 3 --lr 0.0001 --batch_sz 60 --jitter_brightness 0.1 --jitter_contrast 0.1 --jitter_saturation 0.1 --jitter_hue 0.1 --max_num_kmeans_samples 10000000 --no_sobel --include_rgb --input_sz 200 --isola_patch_side 11 > gnodee3_gpu32_m532.out &`

537 Potsdam
`export CUDA_VISIBLE_DEVICES=2,3 && nohup python -m code.scripts.segmentation.baselines.isola --model_ind 537 --arch SegmentationNet10aIsola  --dataset Potsdam --dataset_root /scratch/local/ssd/xuji/POTSDAM --gt_k 6 --lr 0.00001 --batch_sz 60 --jitter_brightness 0.1 --jitter_contrast 0.1 --jitter_saturation 0.1 --jitter_hue 0.1 --max_num_kmeans_samples 10000000 --no_sobel --include_rgb --input_sz 200 --isola_patch_side 11 > sh14_gpu23_m537.out &`

**Comment by SDNAFIO** [comment]
Thank you very much this is exactly what I have been looking for.

Just one more follow-up question:
Is there any specific reason why for the Doersch baselines the --use_doersch_datasets flag was not set?

**Comment by xu-ji** [comment]
It is set to True in the [Doersch script](https://github.com/xu-ji/IIC/blob/ec2cec097408c872b54699e0130356f7e25e7505/code/scripts/segmentation/baselines/doersch.py#L98).
