### ISSUE TITLE
Issue about restart_from_best

### ISSUE THREAD

**Issue by primecai** [xu-ji/IIC#57]
Hello,

I noticed that in the script, while using restart_from_best, there is a check for whether the config.last_epoch correspond to the best epoch.
https://github.com/xu-ji/IIC/blob/b7470a09a6b8d04eb87bf393cc7e4552acc70692/code/scripts/cluster/cluster_sobel_twohead.py#L205
However I did not see anywhere in the code that update config.last_epoch when is_best? Such update only happen when the model saving is done via save frequency.

Many thanks.

**Comment by xu-ji** [comment]
I think you are right. I've now removed that line from the scripts.
