### ISSUE TITLE
About the VAE performance in Table 1

### ISSUE THREAD

**Issue by ZENGXH** [xu-ji/IIC#58]
Hi Xu, 

Thanks so much for your great work! 

I am wondering if you could provide more information about the VAE model you obtain 83.2 on MNIST in your Table 1? 

I am trying to reproduce the number but it seems a naive implementation (i.e., a 784-200-200 enc and 200-200-784 dec, with k-means performed on the 200D mean of the Normal distribution for q(z|x) ) only gets 59% on MNIST.

**Comment by xu-ji** [comment]
Hi, the AE numbers were obtained from table 3 the [DAC paper](http://openaccess.thecvf.com/content_ICCV_2017/papers/Chang_Deep_Adaptive_Image_ICCV_2017_paper.pdf).

**Comment by ZENGXH** [comment]
Got it. Thanks!
