### ISSUE TITLE
How to use the loss without mask?

### ISSUE THREAD

**Issue by ifeherva** [xu-ji/IIC#60]
For an unlabelled dataset how should one use the loss function? It seem to rely on all_mask_img1 which is not available for my dataset.

**Comment by xu-ji** [comment]
Setting mask to all 1s is same as not using a mask, which we do with [Potsdam](https://github.com/xu-ji/IIC/blob/ec2cec097408c872b54699e0130356f7e25e7505/code/datasets/segmentation/potsdam.py#L207).
