### ISSUE TITLE
How to use this codes and apply own data for command 

### ISSUE THREAD

**Issue by yuchan-san** [xu-ji/IIC#62]
Hi, Thank you for great results as your research.
I have tried to use these code, but I don't understand how to use those because of no description on README.
Could you show me how to use the code as samples, and help me which part I should change for own data?

I found the train command in examples.
e.g.

> export CUDA_VISIBLE_DEVICES=2 && nohup python -m code.scripts.cluster.cluster_sobel_twohead --model_ind 640  --arch ClusterNet5gTwoHead --mode IID --dataset CIFAR10 --dataset_root /scratch/local/ssd/xuji/CIFAR --gt_k 10 --output_k_A 70 --output_k_B 10 --lamb 1.0 --lr 0.0001  --num_epochs 2000 --batch_sz 660 --num_dataloaders 3 --num_sub_heads 5 --crop_orig --rand_crop_sz 20 --input_sz 32 --head_A_first --head_B_epochs 2 > out/gnoded1_gpu2_m640_r1.out &

When I run this code, Ive got some results in ./640 directly. However I did not understand that result meanings. And Im not sure the detail of these args, and the procedure.
Please help me for that.

**Comment by xu-ji** [comment]
Hi, the best way to understand is to look at the code. That command links to cluster_sobel_twohead script which is [here](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/cluster_sobel_twohead.py).
For example, the data is loaded [here](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/cluster_sobel_twohead.py#L171).

I made a post on changing the data loading [here](https://github.com/xu-ji/IIC/issues/8#issuecomment-487589581).
