### ISSUE TITLE
'Namespace' object has no attribute 'batchnorm_track'

### ISSUE THREAD

**Issue by keliive** [xu-ji/IIC#63]
Hi,

I have been playing around with the code for a while and I discovered that when I try to load the config files of the pretrained models, some of them fail with the error:

`AttributeError: 'Namespace' object has no attribute 'batchnorm_track'`

It seems that the pretrained models are saved without `batchnorm_track` attribute, but the [classes these models call](https://github.com/xu-ji/IIC/blob/ec2cec097408c872b54699e0130356f7e25e7505/code/archs/segmentation/net10a.py#L69) expect it to be there.

The models that give this error are 482, 487, 496, 521 (there may be more). Out of the models I have tried, only model 544 successfully loads.

Is there any workaround that issue?

Thanks!

**Comment by xu-ji** [comment]
Yes, the default value for batchnorm_track should be True. Set for example [here](https://github.com/xu-ji/IIC/blob/ba23d5930e6af60b2e7e76d7051a47dbba4e751a/code/scripts/cluster/cluster_sobel_twohead.py#L163).

**Comment by xu-ji** [comment]
The best way to check is to simply load the model and print the `track_running_stats` field of the batchnorm modules. They should all be either True or False.
