### ISSUE TITLE
Deepcluster Results in Table 1

### ISSUE THREAD

**Issue by lusensama** [xu-ji/IIC#66]
Hello, Xu. 

Very interesting work here! But I have one issue with the results in the Table 1.
In table 1, how do you evaluate the "Results obtained using our experiments with authors’ original code"?
Or more specifically, how do you do the many-to-one mapping using DeepCluster code? 

Thank you very much.
Sen

**Comment by xu-ji** [comment]
Table 1 doesn't use many-to-one mappings, only one-to-one mappings, to keep it fully unsupervised. (Many-to-one mappings are only used in the semisupervised overclustering mode as this makes material use of labels.)

DeepCluster's eval also finds the best one-to-one mapping ([code](https://github.com/xu-ji/deepcluster/blob/master/utils/clustering/assess_acc.py#L6)).

**Comment by lusensama** [comment]
> Table 1 doesn't use many-to-one mappings, only one-to-one mappings, to keep it fully unsupervised. (Many-to-one mappings are only used in the semisupervised overclustering mode as this makes material use of labels.)
> 
> DeepCluster's eval also finds the best one-to-one mapping ([code](https://github.com/xu-ji/deepcluster/blob/master/utils/clustering/assess_acc.py#L6)).

Thank you for the response! May I know what was the 'arg.gt_k' value that you have used to obtain your table value for CIFAR10?

**Comment by xu-ji** [comment]
10 because the dataset has 10 ground truth classes.

**Comment by lusensama** [comment]
I see. 
My understanding of the deepcluster is that they compute the generated features and then do the k-mean clustering on those features. Are you doing the accuracy assessment (mapping of clusters to the class labels) immediately after this? Correct me if I am wrong.

**Comment by xu-ji** [comment]
Yes I believe so.

**Comment by lusensama** [comment]
Thank you!

**Comment by lusensama** [comment]
Sorry for reopening the issue, I have another quick question. 

Did you use VGG16 to evaluate the result of Deepcluster in Table 1? AlexNet seems to be unused.

Thanks.

**Comment by xu-ji** [comment]
I think we used the same architectures as IIC used for fairness, so [vgg](https://github.com/xu-ji/deepcluster/blob/master/models/new/clustering/deepcluster_net6c_v288.py) and [resnet](https://github.com/xu-ji/deepcluster/blob/master/models/new/clustering/deepcluster_net5g_v288.py).
