### ISSUE TITLE
Running with unknown number of classes

### ISSUE THREAD

**Issue by rggs** [xu-ji/IIC#67]
Reading through the code, it seems that one needs to provide the number of output classes, for example:
`--output_k_B = 10`
Would it be possible to do this without that? I'm attempting to cluster similar images together in an undefined number of possible classes to identify outliers.

**Comment by xu-ji** [comment]
There are many ways you could try to do this, but as we didn't do it you would need to implement it.

One simple way is simply try different numbers of clusters, 2, 4, 8, 16 etc. Find the best one using a metric of your choice, e.g. lowest IIC loss if you don't have ground truth.

Or, simply set the number of clusters as some upper bound, e.g. 128. Out of these 128 clusters, some will probably have very few images assigned. You might expect that outlier probability for an image is inversely correlated to number of other images in its cluster.

**Comment by rggs** [comment]
Great, thank you! I'll see if I can make it work.

**Comment by rggs** [comment]
Ok so I'm running into assertion errors. Because my classes are unknown, I assigned each image an integer as its target rather than its known class. However, this gives me the following error:
``` 
 File "/content/drive/My Drive/Wav_IIC/code/utils/cluster/eval_metrics.py", line 71, in _acc

    assert (preds.max() < num_k and targets.max() < num_k)

AssertionError

```
It would seem giving each image its own unique target number was the wrong thing to do, so what would you recommend instead? I know it's possible because the whole point is the network is unsupervised, I've just been unable to track down how.

**Comment by xu-ji** [comment]
If all your data is unlabelled, you won't be able to run `cluster_eval`, as with no labels there's no way to evaluate accuracy. You can remove those calls in the script, then `targets` should not matter.

**Comment by rggs** [comment]
I tried it with every target being 1, so as long as I don't load the "best" model and only use the "latest", the effect should be the same, right?

**Comment by xu-ji** [comment]
Yes (I think you could even use 0). But it'll be faster if you delete the eval calls.

**Comment by rggs** [comment]
Great thank you so much for the help!

**Comment by rggs** [comment]
And can I assume that the order in which predictions are given is the same order they are presented in the dataset, i.e. if I sorted my images by name then the first soft_predds row would correspond to the first image in alphabetic order?

**Comment by xu-ji** [comment]
Yes but it's not sorted by name.

If you give an input of size (n, c, h, w) containing n images, the predictions will be size (n, k) for k clusters, and each i<sup>th</sup> row in the prediction corresponds to the image in the i<sup>th</sup> row of the input.

**Comment by rggs** [comment]
The array soft_preds seems to have twice as many entries as images I'm giving it. Is that because there is a head A and head B? And should I simply use the first half?

**Comment by xu-ji** [comment]
The result of one call of the network should have exactly as many entries as images. The only reason that comes to mind is maybe you have 2 subheads? `--num_sub_heads 1` would change this

**Comment by rggs** [comment]
I actually have 5 subheads, so I don't think it's that. It's very odd. Worst comes to worst, I could always load the net into a different script and feed the images through manually rather than saving the predictions through the save_progress attribute.
