### ISSUE TITLE
What is the format of the data for dataloader

### ISSUE THREAD

**Issue by lemonci** [xu-ji/IIC#68]
Hi, I am a historian who would like to employee the clustering function for clustering different types of signatures like these (around 500 images in total, some of them are made by the same person):
![image](https://user-images.githubusercontent.com/22335260/85405961-b03f9b80-b593-11ea-943d-157021fd1308.png)
![image](https://user-images.githubusercontent.com/22335260/85406032-c9484c80-b593-11ea-8a3a-8a644e35ef58.png)
![image](https://user-images.githubusercontent.com/22335260/85406061-d2d1b480-b593-11ea-930e-4583a1503d5f.png)
I think the most likely dataset for my task is MNIST, so I would like to know the format of the data in the data loader function for MNIST. Say, should I save all of the images as csv matrix or just png files after I do all the resizing, rgb2gray and whitening task?
Also, as there are no labels for the data and we are not sure how many clusters are rational for this task, may I ask how to drop off the evaluation flag and output the relative distance between samples?
I have read your answer in https://github.com/xu-ji/IIC/issues/8 and am still puzzled at this stage. Thanks a lot.

**Comment by xu-ji** [comment]
Edit my script to change the [data loading](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/cluster_greyscale_twohead.py#L179), the best way to see how this works in detail is to just follow the function call and read the code. You will need your own dataset class to load the data, can't reuse torchvision.datasets.MNIST. For example, it's fairly simple to write your own subclass of [torch.utils.data.Dataset](https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset), or use [torchvision.datasets.ImageFolder](https://pytorch.org/docs/stable/torchvision/datasets.html#torchvision.datasets.ImageFolder).

To remove evaluation, delete all calls to  `cluster_eval, get_subhead_using_loss` in the script.

To get the relative distance between 2 images, simply run both through your trained network (in eval mode, i.e. call network.eval()) to get 2 prediction vectors, and take L2 norm of the difference as distance. Lastly if you train with `--batchnorm_track` (unlike what I did for the MNIST results), the network output will be invariant to batch statistics in eval mode, which is more convenient, so I recommend it.

**Comment by lemonci** [comment]
Thanks for your reply. I have checked the [PyTorch Custom Dataset Examples](https://github.com/utkuozbulak/pytorch-custom-dataset-examples) and found the images must have labels to construct. So I wonder if I can just assign a uniform trivial label to all the samples and just ignore the evaluation part. 
After reading [code/utils/cluster/data.py](https://github.com/xu-ji/IIC/blob/ec2cec097408c872b54699e0130356f7e25e7505/code/utils/cluster/data.py), may I ask `config.train_partitions_head_B` refers to the Optional over clustering part in Fig 2 of the paper? If yes, what we can do to discharge it, as all the data in the customized dataset need to be clustered.
Regarding employing the L2 norm as the relative distance between each pair of images, actually I wonder how to measure the distribution of all the sample points in the space apart from the visualisation approach with PCA. I admit it a bit tricky as the data has no label, so an objective evaluation like the accuracy rate in the IIC paper is not applicable.

**Comment by xu-ji** [comment]
> if I can just assign a uniform trivial label to all the samples and just ignore the evaluation part.

For the training data, yes I think so.

> `config.train_partitions_head_B`

`head_B` refers to the main output head. `head_A` refers to the auxiliary overclustering head (optional part of figure 2). Actually, we used auxiliary overclustering in all experiments even when the data for the two heads is the same, because it improves performance even in this case and I recommend it. See last sentence in section 3.2.  But if you want to remove it, change the script to `heads = ["B"]` and `for head_i in range(1):`.

> measure the distribution of all the sample points in the space

Actually we didn't use PCA. E.g. in figure 3 we render raw predictions, the projection is just to turn a 10D prediction into a 2D coordinate using a fixed circle guide. Yes, evaluation is hard without labels. You could manually label a small subset of your data and compare against this; otherwise, manual inspection of results.

**Comment by lemonci** [comment]
Thanks a lot for the patient and prompt response. I have tried to add my own dataset using `torchvision.datasets.ImageFolder`. However, it seems that there was only one grayscale dataset in your experiments so you fixed the codes in [cluster_greyscale_twohead.py](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/cluster_greyscale_twohead.py) specific for MNIST from Line 117. May I ask what to change for a grayscale dataset, or should I directly use cluster_sobel_twohead.py directly even for grayscale images? Thanks a lot.

**Comment by xu-ji** [comment]
The key difference is the greyscale scripts use `sobel=False`, i.e. no sobel filtering as pre-processing, as it's not RGB. I'm not sure what difference it would make for your dataset. Since your data seems to be in colour you could try `cluster_sobel_twohead.py` with sobel filtering.

**Comment by lemonci** [comment]
> The key difference is the greyscale scripts use `sobel=False`, i.e. no sobel filtering as pre-processing, as it's not RGB. I'm not sure what difference it would make for your dataset. Since your data seems to be in colour you could try `cluster_sobel_twohead.py` with sobel filtering.

Hi, actually I have converted the dataset to be grayscale as I used some whitening tricks to increase the contrast. So in that case, I would like to know how to change `cluster_greyscale_twohead.py` to use other dataset apart from MNIST, as you wrote something like `assert ("MNIST" == config.dataset) ` etc.

**Comment by xu-ji** [comment]
You should feel free to change the code, to adapt it for your dataset. Remove `assert ("MNIST" == config.dataset)`, it's just a sanity check.

**Comment by lemonci** [comment]
So sorry to bother you that much. I tried to save each type of my images into a folder and used 
```
    sig_dataset = torchvision.datasets.ImageFolder('path_to_image_folder')

    dataset_class = torch.utils.data.DataLoader(sig_dataset)
```
 trying to load the data and here comes the error
```
  File "/home/monica/IIC/code/scripts/cluster/cluster_greyscale_twohead.py", line 495, in <module>train()

  File "/home/monica/IIC/code/scripts/cluster/cluster_greyscale_twohead.py", line 181, in train cluster_twohead_create_dataloaders(config)

File "code/utils/cluster/data.py", line 94, in cluster_twohead_create_dataloaders target_transform=target_transform)

File "code/utils/cluster/data.py", line 287, in _create_dataloaders target_transform=target_transform)

TypeError: 'DataLoader' object is not callable

```

So I think the `dataset_class` variable must need to have something different from direct reading via 'torchvision.datasets.ImageFolder'. I tried to read the code of [MNIST](https://pytorch.org/docs/1.1.0/_modules/torchvision/datasets/mnist.html) but there are too many functions that I got lost. Actually I am not sure how to load training/testing data as 'torchvision.datasets.ImageFolder' won't distinguish training/testing data itself. Thanks for your help.

**Comment by xu-ji** [comment]
That error arose because dataset_class is supposed to be the actual class rather than an instance of the class.

I wrote [a function](https://github.com/xu-ji/IIC/blob/81a9d595ee423ae5e29609c89cb09fc470dae689/code/utils/cluster/data.py#L502) to help you, this should be simpler to use.

**Comment by lemonci** [comment]
Thanks a lot for your kind help. I would like to confirm the data structure of `mapping_assignment_dataloader` and `mapping_test_dataloader`, or to say, what I should put in the ImageFolder root path for these two to generate the two variables for evaluation.

**Comment by xu-ji** [comment]
I think you said you have no labelled images, so you can't use the default evaluation in the code. You can just leave it as nonexistent directory `"none"`, which will result in [mapping data loaders being None](https://github.com/xu-ji/IIC/blob/81a9d595ee423ae5e29609c89cb09fc470dae689/code/utils/cluster/data.py#L556). And remember to delete the calls to `cluster_eval, get_subhead_using_loss` in the main script.

**Comment by lemonci** [comment]
> Edit my script to change the [data loading](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/cluster_greyscale_twohead.py#L179), the best way to see how this works in detail is to just follow the function call and read the code. You will need your own dataset class to load the data, can't reuse torchvision.datasets.MNIST. For example, it's fairly simple to write your own subclass of [torch.utils.data.Dataset](https://pytorch.org/docs/stable/data.html#torch.utils.data.Dataset), or use [torchvision.datasets.ImageFolder](https://pytorch.org/docs/stable/torchvision/datasets.html#torchvision.datasets.ImageFolder).
> 
> To remove evaluation, delete all calls to `cluster_eval, get_subhead_using_loss` in the script.
> 
> To get the relative distance between 2 images, simply run both through your trained network (in eval mode, i.e. call network.eval()) to get 2 prediction vectors, and take L2 norm of the difference as distance. Lastly if you train with `--batchnorm_track` (unlike what I did for the MNIST results), the network output will be invariant to batch statistics in eval mode, which is more convenient, so I recommend it.

Sorry to occupy you so much time. As you mentioned in the previous reply, the only way to examine the L2 norm is using eval mode. However, as you suggested in the last reply, the functions related to evaluation have all been commented out. In that case, may I ask what does `--batchnorm_track` do? It seems it just help to do a batch normalization [in the training process](https://github.com/xu-ji/IIC/blob/ec2cec097408c872b54699e0130356f7e25e7505/code/archs/cluster/vgg.py#L29), so I do not quite understand how it helps in the evaluation. Actually, I would like to know the L2 norm between images because I would like to manually see how the IIC model treats two images as similar (It could be an irrational thing to do but it could be more explainable).
Also, may I ask which flag we should use to get the clustering result/probability for each cluster of all the samples for the whole dataset for unsupervised clustering? Should I just use `reordered_preds` in [k_means_assess](https://github.com/xu-ji/IIC/blob/ec2cec097408c872b54699e0130356f7e25e7505/code/utils/cluster/k_means_assess.py#L46), specifically after the model has been trained and saved? Thanks.

**Comment by xu-ji** [comment]
`--batchnorm_track` affects eval time (after calling .eval()) behaviour. If True, normalization statistics are taken from stored training statistics, if False statistics are estimated from each eval batch (so for small eval batches, prediction behaviour is usually different from larger batches - this is bad).

> which flag we should use to get the clustering result/probability for each cluster of all the samples for the whole dataset for unsupervised clustering

`k_means_assess`, this code was for another baseline. Post-processing such as k-means is not necessary with our method, you can take the raw network output as its prediction, which is what we did for all our results. Anything with `reordered` in the name is not relevant as this refers to aligning output clusters (channels) with ground truth, which you don't have. 

You can do the analysis during the network training ([example](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/cluster_greyscale_twohead.py#L273)) or a simple script to do it afterwards on a saved network ([example](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/analysis/print_examples.py)). Again my code is more complex than you want as it does an accuracy evaluation to reorder the output channels. You can just treat cluster 0 as class 0, cluster 1 as class 1 etc. - no need for evaluation or reordering. 

The key idea is just call network.eval(), run your image(s) through the network, get its prediction(s) as network output. After you have this 1xnum_clusters vector per image you can do any sort of printing or rendering you like.

**Comment by lemonci** [comment]
After referred to your example for saved network, I found that I still need to understand how to allocate a valid variable for `mapping_assignment_dataloader` using ImageFolder, otherwise, there is no way to feed the images into the net. As you suggested in [#8](https://github.com/xu-ji/IIC/issues/8): 
- `mapping_assignment_dataloader`: used for evaluation, i.e. similar to `dataloaders_head_B[0]`. This is used to find the 1-1 mapping between output clusters and ground truth classes.

I traced the code to find it created by `_create_mapping_loader`, in that case, I would like to know how to do a replacement for this function using ImageFolder, as long as I have put the images into different "classes" in the subfolders? Thanks.

**Comment by xu-ji** [comment]
`mapping_assignment_dataloader` is only used for `cluster_eval` (and my `save_progress` function), which you should delete and not be calling.

**Comment by lemonci** [comment]
In that case, I think I have some difficulties when following your suggestion “
The key idea is just call network.eval(), run your image(s) through the network, get its prediction(s) as network output.”
as I am not familiar about how to load the trained weights into the network and feed in the images. May I ask if I should refer to the two saved model files in the output files? Thanks.

**Comment by xu-ji** [comment]
Yes. Here's the steps:

1. Create instance of network with random weights. [Example](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/analysis/print_examples.py#L31)
2. Overwrite this network's parameters with saved model. [Example](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/analysis/print_examples.py#L33) 
3. Call net.eval() (and net.cuda() if using GPU). [Example](https://github.com/xu-ji/IIC/blob/master/code/scripts/cluster/analysis/print_examples.py#L36)
4. Load the data you want to get predictions for and run through network
```
data = my_data() # iterable of tensors (image(s), label(s)), for example simple list, or dataset (e.g. ImageFolder) or DataLoader
for inputs, labels in data: # inputs dimensions: (n, c, h, w) or (c, h, w), labels dimensions: (n) or (1) but labels are ignored
  inputs = inputs.cuda() # if using GPU
  if len(inputs.shape) == 3: inputs = inputs.unsqueeze(0) # shape (c, h, w) ->  (1, c, h, w)
  if sobel: # false for greyscale images
    inputs = sobel_process(inputs, config.include_rgb)

  with torch.no_grad(): # turn off gradients support
    predictions = net(inputs) # predictions size: (n, num_clusters) or (1, num_clusters), automatically uses head_B

```

**Comment by lemonci** [comment]
Thanks for the clarifications. I have tried your method and found there's an error returned from `sobel_process`, as it requires `c == 4` for `using_IR=False` in [transforms](https://github.com/xu-ji/IIC/blob/master/code/utils/cluster/transforms.py#L55).
However, the inputs from data only has 3 channels for RGB images, even after unsqueeze. May I how to fillin the missing channel? Thanks.

**Comment by rggs** [comment]
Hey lemonci,
I've been doing a similar project (clustering groups of unlabelled images using a custom Dataset) and I might recommend you make a copy of this project and then modify it there. This guide explains how you can do that:

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository

That way, I or others can suggest changes to your scripts. I would also recommend that you convert your images to grayscale; this is a fairly easy process, but if you'd like some help doing that I am more than happy.

**Comment by xu-ji** [comment]
I thought your images are greyscale (1 channel) now? In which case sobel=False (this is the difference between cluster_greyscale* and cluster_sobel* scripts) because we only use sobel filtering for RGB images.

For rgb, i.e. using sobel filtering, the extra channel is the greyscale image. (Computed as part of [tf1, tf2, tf3](https://github.com/xu-ji/IIC/blob/08a349ec71f3fb15aff79a62a442e7247175e7c1/code/utils/cluster/data.py#L61) which are the transforms run on the dataset when loading). tf3 is the test time transform, it needs to be applied during call to my_data() (I've edited my answer above). Unless of course your tf3 is identity (doing nothing).

**Comment by lemonci** [comment]
> I thought your images are greyscale (1 channel) now? In which case sobel=False (this is the difference between cluster_greyscale* and cluster_sobel* scripts) because we only use sobel filtering for RGB images.
> 
> For rgb, i.e. using sobel filtering, the extra channel is the greyscale image. (Computed as part of [tf1, tf2, tf3](https://github.com/xu-ji/IIC/blob/08a349ec71f3fb15aff79a62a442e7247175e7c1/code/utils/cluster/data.py#L61) which are the transforms run on the dataset when loading). tf3 is the test time transform, it needs to be applied during call to my_data() (I've edited my answer above). Unless of course your tf3 is identity (doing nothing).

Thanks for the help. Finally I got the predictions. Would like to understand the n in `predictions = net(inputs) # predictions size: (n, num_clusters)` Should it be the same as the n in `inputs dimensions: (n, c, h, w) or (c, h, w)`? Because after the unsqueeze, n should be 1 but the shape of the prediction using sobel is (5, num_clusters).

**Comment by lemonci** [comment]
> Hey lemonci,
> I've been doing a similar project (clustering groups of unlabelled images using a custom Dataset) and I might recommend you make a copy of this project and then modify it there. This guide explains how you can do that:
> 
> https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/duplicating-a-repository
> 
> That way, I or others can suggest changes to your scripts. I would also recommend that you convert your images to grayscale; this is a fairly easy process, but if you'd like some help doing that I am more than happy.

Thanks for the help. The repo has been [replicated and changed](https://github.com/lemonci/IIC_c/).

**Comment by xu-ji** [comment]
> Would like to understand the n in predictions = net(inputs) # predictions size: (n, num_clusters) Should it be the same as the n in inputs dimensions

Yes, n is the number of inputs (the size of the batch). If you're doing one image at a time it should be 1. If it's 5, it may be because you are using 5 sub-heads? Try `--num_sub_heads 1`.

**Comment by lemonci** [comment]
Just found out my problem can be better solved by traditional pattern recognition techniques such as watershed. Thanks for your kind help and patience!
