### ISSUE TITLE
Large Dataset being killed

### ISSUE THREAD

**Issue by rggs** [xu-ji/IIC#72]
I am trying to use my own dataset. However, the dataset file is large (~7 GB) and I am running the scripts on Google Colab, so my memory is somewhat limited. When running, the script is killed and the last line in the .out file is:
`Creating auxiliary dataloader ind 0 out of 5 time 2020-07-01 14:04:59.398052`
and I suspect it is due to excessive use of memory. Is there a way I could segment out my dataset so that it is loaded in smaller pieces on demand? Or would the recommendation be to simply reduce the size of my dataset? Currently, it is stored as a large pytorch tensor. Would it be best practice to instead save each item as its own image/tensor to load individually?

**Comment by xu-ji** [comment]
>Would it be best practice to instead save each item as its own image/tensor to load individually?

Before doing that I would try easier options. One or some of these may be enough:

- Reduce number of dataloaders (`--num_dataloaders`)
- Smaller batch size (`--batch_sz`)
- Preprocess your data to reduce the size of the input images.

**Comment by rggs** [comment]
I reduced batch size, number of data loaders, and number of subheads all to 1 but I still get the same issue. The console printout is:
`tcmalloc: large alloc 7386193920 bytes == 0x5498000 @  0x7fccabfefb6b 0x7fccac00f379 0x7fcc531aa04e 0x7fcc531abf4a 0x7fcc8c29b984 0x7fcc9a6f26e9 0x551365 0x5a9cbc 0x50a5c3 0x50bfb4 0x507d64 0x509042 0x5a4b71 0x5a4ec8 0x4e009e 0x50a5f1 0x50bfb4 0x507d64 0x588e5c 0x59fc4e 0x50d356 0x507d64 0x509a90 0x50a48d 0x50bfb4 0x507d64 0x509042 0x594931 0x549e5f 0x5513d1 0x5a9cbc

tcmalloc: large alloc 7386193920 bytes == 0x1be12a000 @  0x7fccabfefb6b 0x7fccac00f379 0x7fcc531aa04e 0x7fcc531abf4a 0x7fcc8c29cf3b 0x7fcc8c2af1c3 0x7fcc8c3075c0 0x7fcc8c1dc121 0x7fcc8c17fa32 0x7fcc8c195fc4 0x7fcc8dc235ff 0x7fcc8c195fc4 0x7fcc9a408227 0x50a635 0x50bfb4 0x507d64 0x509042 0x594931 0x549e5f 0x5513d1 0x5a9cbc 0x50a5c3 0x50cd96 0x507d64 0x509a90 0x50a48d 0x50cd96 0x509758 0x50a48d 0x50bfb4 0x5060d4

tcmalloc: large alloc 14772379648 bytes == 0x376530000 @  0x7fccabfefb6b 0x7fccac00f379 0x7fcc531aa04e 0x7fcc531abf4a 0x7fcc8c29cf3b 0x7fcc8c2af1c3 0x7fcc8c307616 0x7fcc8c1dc121 0x7fcc8c17fa32 0x7fcc8c195fc4 0x7fcc8dc235ff 0x7fcc8c195fc4 0x7fcc9a408227 0x50a635 0x50bfb4 0x507d64 0x509042 0x594931 0x549e5f 0x5513d1 0x5a9cbc 0x50a5c3 0x50cd96 0x507d64 0x509a90 0x50a48d 0x50cd96 0x509758 0x50a48d 0x50bfb4 0x5060d4

/bin/bash: line 1:  1032 Killed                  python3 -m code.scripts.cluster.cluster_greyscale_twohead --model_ind 501 --arch ClusterNet6cTwoHead --mode IID --dataset WAVELET --dataset_root '/content/drive/My Drive/Wav_IIC/datasets/wavelets' --gt_k 50 --output_k_A 50 --output_k_B 50 --lamb_A 1.0 --lamb_B 1.0 --lr 0.0001 --num_epochs 100 --batch_sz 1 --num_dataloaders 1 --num_sub_heads 1 --crop_orig --crop_other --tf1_crop centre_half --tf2_crop random --tf1_crop_sz 20 --tf2_crop_szs 16 20 24 --input_sz 24 --rot_val 25 --no_flip --out_root '/content/drive/My Drive/Wav_IIC/out' --head_B_epochs 2 --save_progress --save_freq 1 --one_tnsr > '/content/drive/My Drive/Wav_IIC/out/50_1classes_50epoch_gpu.out'`

And the last line in the .out file is:
`Making datasets with <class 'datasets.wavelets.wavelet_dset.WaveletDataset'> and None`

**Comment by rggs** [comment]
It's also worth noting that I have reason to keep the images at their full resolution.

**Comment by xu-ji** [comment]
I think your dataset is too large to fit in RAM in one go. In this case yes, change your dataset code so that `__getitem__` loads from file on demand.

**Comment by rggs** [comment]
Ok, I've made those changes, although now it gets to the line where it says "Number of batches per epoch" and then gets stuck (it continues to run but it's been going for hours and nothing has changed). Do you have any idea what it might be hanging on?

```
Making datasets with <class 'datasets.wavelets.wavelet_dset.WaveletDataset'> and None

Creating auxiliary dataloader ind 0 out of 5 time 2020-07-06 13:59:22.720741

Creating auxiliary dataloader ind 1 out of 5 time 2020-07-06 14:01:22.819900

Creating auxiliary dataloader ind 2 out of 5 time 2020-07-06 14:03:22.943436

Creating auxiliary dataloader ind 3 out of 5 time 2020-07-06 14:05:23.037529

Creating auxiliary dataloader ind 4 out of 5 time 2020-07-06 14:05:49.871076


Length of datasets vector 6

Number of batches per epoch: 5250

Creating auxiliary dataloader ind 0 out of 5 time 2020-07-06 14:05:52.259554

Creating auxiliary dataloader ind 1 out of 5 time 2020-07-06 14:05:53.561712

Creating auxiliary dataloader ind 2 out of 5 time 2020-07-06 14:05:54.839132

Creating auxiliary dataloader ind 3 out of 5 time 2020-07-06 14:05:56.051383

Creating auxiliary dataloader ind 4 out of 5 time 2020-07-06 14:05:57.347993

Length of datasets vector 6

Number of batches per epoch: 5250
```

I've tried reducing the number of dataloaders etc. but even with 2 dataloaders and 420 batches per epoch it seems to be getting stuck.

**Comment by rggs** [comment]
Could it be getting stuck on the cluster eval part? I am running with a dataset that is not prelabeled, so each "target" is simply a number (given sequentially by the file order), rather than an integer assigning it to a particular class.

**Comment by rggs** [comment]
Gonna go ahead and close this because my best guess is the dataset is just very large.

**Comment by xu-ji** [comment]
For Potsdam we split the huge 6000x6000pixel images into 15x15 squares and halved resolution to make it more computationally feasible.

You can use printing with datetime.now() and sys.stdout.flush() to pinpoint wherever it's getting stuck.

**Comment by rggs** [comment]
It's odd, because it seems to be done making the dataloaders_head_B because it prints: 
```
Making dataloaders head B. time 2020-07-08 13:57:45.003387: 
Creating auxiliary dataloader ind 0 out of 5 time 2020-07-08 13:57:46.069466
Creating auxiliary dataloader ind 1 out of 5 time 2020-07-08 13:57:47.092041
Creating auxiliary dataloader ind 2 out of 5 time 2020-07-08 13:57:48.123719
Creating auxiliary dataloader ind 3 out of 5 time 2020-07-08 13:57:49.186460
Creating auxiliary dataloader ind 4 out of 5 time 2020-07-08 13:57:50.239847
Length of datasets vector 6
Number of batches per epoch: 10500
```

But then I put a print statement above the creation of mapping_assignment_dataloader, and it doesn't print that:
```
print('Mapping test dataloader. time %s: ' % (datetime.now()))

mapping_test_dataloader = \
  _create_mapping_loader(config, dataset_class, tf3,
                         partitions=config.mapping_test_partitions,
                         target_transform=target_transform)
```
So it's almost as if the return part of the dataloaders_head_B is what it's hanging on, even though it has no trouble doing the dataloaders_head_A, and when running it with the smaller dataset (~2,000 images, but with the same resolution), it runs with no issues:

```
Making dataloaders head B. time 2020-07-08 15:06:09.628234: 
Creating auxiliary dataloader ind 0 out of 5 time 2020-07-08 15:06:09.666383
Creating auxiliary dataloader ind 1 out of 5 time 2020-07-08 15:06:09.703534
Creating auxiliary dataloader ind 2 out of 5 time 2020-07-08 15:06:09.740291
Creating auxiliary dataloader ind 3 out of 5 time 2020-07-08 15:06:09.778300
Creating auxiliary dataloader ind 4 out of 5 time 2020-07-08 15:06:09.816594
Length of datasets vector 6
Number of batches per epoch: 113
Mapping assignment dataloader. time 2020-07-08 15:06:09.855334: 
Mapping test dataloader. time 2020-07-08 15:06:09.895951: 
```

I'm not sure at this point if my only option is to downsize the images, or if it's possible to restructure the net to get around that.
