### ISSUE TITLE
which dimension loss is calculated???

### ISSUE THREAD

**Issue by anish9** [xu-ji/IIC#77]
Hi,
 I have been trying to break the algorithm and found confusing on loss calculation(IIC), my doubt is, lets assume my batch size is 16 and cluster heads are 8 , so my final layer prediction shape is (16,8), from here my question should i pass the matrix for computation with same(including batch) or perform loss operation in individual pairs. your guidance would be helpful !

Thanks,

**Comment by xu-ji** [comment]
Actually there should be one 16xC matrix per sub-head, where C is number of clusters. So total dimensions would be 8 * 16 * C or similar.

The loss is computed over the entire batch. Because it includes an expectation over all samples in the batch.

**Comment by anish9** [comment]
Thanks for the explanation, indeed it helped me but, should size of sub-heads and cluster classes should be same or  can be also a different value.

**Comment by xu-ji** [comment]
They can be different. If you want a simple set up just use 1 sub-head (--num_sub_heads 1).

**Comment by anish9** [comment]
Thanks again !!!
