### ISSUE TITLE
best train subhead match

### ISSUE THREAD

**Issue by sc-56** [xu-ji/IIC#79]
Sorry for bothering again, 

may I roughly know how to understand 'best_train_sub_head_match'
ex. the number is like: [(0, 0), (1, 19), (2, 14), (3, 8), (4, 18), (5, 9), (6, 17), (7, 11), (8, 16), (9, 10), (10, 4), (11, 12), (12, 5), (13, 3), (14, 7), (15, 2), (16, 13), (17, 6), (18, 1), (19, 15)]

Thank you so much for your support.

**Comment by xu-ji** [comment]
It's the best one-to-one mapping from output clusters to ground truth classes, according to whatever labelled data was in `mapping_assignment_dataloader`. Each element (a, b) means output channel a should be considered as ground truth class b.

**Comment by sc-56** [comment]
thank you for your detailed explanation.

I'm curious if I wish to do the analysis related to this ( like you conduct in the paper, or similar ), would you like to provide some advise of the method? 

thank you in advance for your support.
