### ISSUE TITLE
About the segmentation metrics acc

### ISSUE THREAD

**Issue by forrestsz** [xu-ji/IIC#81]
Hi, thank for your awesome work 👍 . when I reading your paper, i have a little question, How to compute the acc for dataset like postdam3?  the code your write a little abstract for me, I am sorry for this.
As i understood, I should compute the acc for each image to get `acc_i`, and then, the total `acc_total` equal to `acc_i/num`. Am i right?

**Comment by xu-ji** [comment]
The segmentation accuracy we used was just (total number of correct pixels)/ (total number of pixels), across the whole test set. 
We didn't do it on a per image basis, though if the number of predictions per image is constant, this would be equivalent. For COCO-Stuff the number of valid pixels per image was variable, so it's not equivalent in this case. For potsdam, where every pixel of every image was used, it is equivalent.

**Comment by forrestsz** [comment]
ok, thank you. I will take your advice. 👍
