### ISSUE TITLE
Issue on running with Custom Dataset

### ISSUE THREAD

**Issue by praneet195** [xu-ji/IIC#84]
There are a few issues on running with a  custom dataset:
1) Deterministic Random Sampler needs an additional argument  (data_source)
2) print("Pre: time %s: \n %s" % (datetime.now(), nice(config.epoch_stats[-1])))
IndexError: list index out of range
How do I fix these?

**Comment by xu-ji** [comment]
So sorry for the late reply.

1. I've changed it now.
2. It's trying to print before config.epoch_stats has anything in it. All the printing is just for diagnostics, you can comment it out.

**Comment by praneet195** [comment]
Thank you
