### ISSUE TITLE
Problem with dataloaders

### ISSUE THREAD

**Issue by nhuvan** [xu-ji/IIC#92]
Hi @xu-ji ,
Thank you so much for your work and sharings.
I have tried to train the clustering model on a custom dataset using your function  "create_basic_clustering_dataloaders" but I can not get out of this error:

`TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'torchvision.datasets.folder.ImageFolder'>`

Do you have any idea on this ?

**Comment by xu-ji** [comment]
Can you give the full error trace? Including line number, file etc.

**Comment by nhuvan** [comment]
Thank you, I used wrong dataloader. It is ok now.

**Comment by WinnieLaugh** [comment]
Hi  @nhuvan,

How did you solve this problem? I got this same error and could not find out where I went wrong.
