### ISSUE TITLE
Reproduce the final results

### ISSUE THREAD

**Issue by cailk** [xu-ji/IIC#94]
Dear @xu-ji ,
Thank you for your brilliant work. I have trained the IIC network, and have some questions about reproducing the final results:
1) Are the parameter settings of CIFAR-10-clustering shown in "IIC/examples/commands.txt" same as the settings in paper? Or are there always exists some fluctuations in final results? It seems like I can't reproduce the best acc 61.7 on CIFAR-10 dataset. I only got 59.01% best acc.
2) Is there any possibility you update a python3 version code? Or have you test the performance of code in this repo [https://github.com/sebastiani/IIC](url)?

Sorry to bother. Looking forward to your reply.

**Comment by xu-ji** [comment]
1. There will be some variation. I did not set some random seed for perfect reproducibility; I should have.
2. I want to leave it as it was when I did the work. But I don't think the changes to python3 syntax are very complicated. I have not tested that repository you linked.
