### ISSUE TITLE
Do you have any advice on how to find the best transformation for a particular dataset with no labels?

### ISSUE THREAD

**Issue by vivektreddy** [xu-ji/IIC#95]
Do you have any advice on how to find the best transformation of a given dataset if there are no labels?  
Right now, I am training with a subset of data of only about 300 images and visualizing the clusters.  I am training this until I get a reasonable loss value, then visualizing the groupings.  Then, I'm tweaking a value such as changing rotation from 30 to 60 and visualizing it again and seeing what's changed.  Is there a better way to find best transformations that will work best for a dataset?  Thank you.

**Comment by xu-ji** [comment]
I would recommend, generally, trying to go for the strongest transformations that still reasonably preserve the information in the image. But this is not really possible to predetermine formulaically, so I think trial and error is the way to go in practice.

**Comment by vivektreddy** [comment]
Thank you. So is the additional lambda term like regularization?
 I(z,z') + (lambda-1) * ( H(z) + H(z')). 
Does this lambda act like a penalty term that forces H(z) and H(z') values to be higher and H(z|z') not to be focused on? What does this mean theoretically? How would it change the cluster space? Thank you.

**Comment by xu-ji** [comment]
Yes, higher lambda means biasing towards entropy. It means that in the trade-off between predictive sureness despite transformation corruption (H(z|z')) and even spread (H(z)), the latter will be prioritized. If lambda is high enough, and let's say there are c clusters, one could imagine the network would try to partition its inputs into c equal sized blocks irrespective of the semantic invariances we are trying to learn.
